### ISSUE TITLE
For restricted categories, add more impedance for users who can't post

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#1091]
Based on https://meta.codidact.com/posts/288795:

If a category restricts who can create posts, you get an error message when you click the button.  I understand why we do it that way -- only do the check on the infrequent action and not on every page load -- but is there a *performant* way to push this check up and not show the button if the user won't be allowed to post?  Failing that, can we change something about the rendering of the button (for everyone) that would signal "something special about this one"?  I'm not sure what would be reasonable -- maybe adding the lock icon like on the category banner?

**Comment by trichoplax** [comment]
Related:
- https://meta.codidact.com/posts/287836

**Comment by trichoplax** [comment]
I wouldn't expect performance to be a significant issue here. Most pages are already checking server side whether the user is signed in, checking what abilities they have to decide whether to render "Edit" or "Suggest Edit", whether to show moderator tools, which indicator circles to display - checking one more ability server side shouldn't be a problem.

Just mentioning this so the discussion can be about what works for the user rather than being a compromise with optimisation.

**Comment by cellio** [comment]
Duplicate of https://github.com/codidact/qpixel/issues/994 .  I even asked the related Meta question and then forgot.  (Smacks forehead.)
