### ISSUE TITLE
Putting $$ around text when pressed

### ISSUE THREAD

**Issue by Wouter17** [codidact/qpixel#1266]
**Is your feature request related to a problem? Please describe.**
When reformatting posts containing math (but not yet in LaTeX) into LaTeX, I'll need to place a dollar sign on both ends of the math expression. I think this can be simplified and made more accessible.

**Describe the solution you'd like**
When a user has some text selected and the `$` key is pressed, it would be nice if the text select would have dollar signs placed before and after it, similar to how the `ctrl+b` shortcut works for `*`.

**Describe alternatives you've considered**
An alternative would be to add a shortcut (like `ctrl+b` for `*`). As far as I know however, there is no established shortcut for adding `$` so users would have to learn this shortcut.

**Comment by cellio** [comment]
And/or add a button to the editor like we have for bold, italic, etc -- if text is selected and you click one of those it applies that formatting to the selected text.

We would want to enable this -- both the shortcut and the button -- only on sites that have MathJax enabled.  Otherwise it'll confuse people.
