### ISSUE TITLE
Freely-editable posts shouldn't be deletable by original posters

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#1394]
Arises from https://proposals.codidact.com/posts/292485:

Our network defines a Wiki post type, which has the "freely editable" flag set.  By design, these posts are "owned" by the community, though obviously they are created by specific users.  Currently, the creator can delete it (because the creator is the owner), but the philosophy behind "freely editable" is that the post is "owned" by the community regardless of which user accounts are attached to it.

If a post type is "freely editable", it should be treated as "not your post" if you try to delete it.  If you have the ability to delete posts in general, you can still delete, but if you wouldn't be able to delete another user's post, you also shouldn't be able to delete a wiki post.

**Comment by ws909** [comment]
Eventually, I think it’s worth rethinking user cards under posts, and how we do post attribution in general. Only a few posts really need to be owned by a specific user. And in the end, we do kind of operate with the idea that the community always owns your post, which is why we’ll undelete useful posts even if the author demands their deletion.
