### ISSUE TITLE
Let's limit or truncate super-long user names

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#146]
Our tester has produced the following:

Comment: 

![comment w/10-line user name](https://user-images.githubusercontent.com/5557942/91112578-7b15ff00-e651-11ea-841a-05d168dcc23d.png)

Post: 

![long user name prevents usercard formatting on post](https://user-images.githubusercontent.com/5557942/91112596-89641b00-e651-11ea-9255-4439d6b30918.png)

And the user page; note the size of the horizontal scrollbar:

![very wide page](https://user-images.githubusercontent.com/5557942/91112717-de079600-e651-11ea-99af-1beee216539f.png)

We should probably prevent that from rendering like that.  I think we do have a reasonable-ish limit on the length of user names, but special character encodings might be in play here.  I'm not sure what limitations make sense; maybe we can instead truncate where necessary?  Is that possible?  Can we, in the UI, give an element a bounding box and say "you must fit within this space", so the rest of the page displays ok?

**Comment by chindraba-work** [comment]
Rather than try to limit the visual length of a user name, which seems problematic to implement without "knowing" all the possibilities for extending the visual withing a constrained character limit, just place the display of user names in a constrained box with overflow hidden. Reduces the effect of the occasional use of Zalgo text as well.

**Comment by kevinmmansour** [comment]
Since we are in 2021, so we have to add limit for long usernames or add container for them but I like to limit them?

I think about 15 Characters is fine or maybe 20 Characters .

**Comment by cellio** [comment]
Here is another place where this causes problems:

![users list, long name in left column pushes right out of the frame](https://user-images.githubusercontent.com/5557942/149264822-547ce58e-ffc6-4cb2-8fa8-764bea2ba9de.png)

A long user name in the left-most column pushes the other two columns over.  But we're not falling back to two columns if three don't fit; instead, the third (right-most) column is wider than its container and so the names are truncated.

I don't think we should try to limit names by visual display; with Unicode that'd be hard.  I think we should limit how much space we give a user name in all the places we show it, truncating the name if necessary.

**Comment by Trilarion** [comment]
The user name in the screenshot q4q0... is 36 characters long. Not sure that the current limit on the length of user names is and what a reasonable length limit would be. I can probably check SEDE and see how long the smallest 95% of usernames on SO are as a reasonable value.

Additionally in the user list we have three columns and width 960 px but behind names there are potentially also badges (mod, staff, ..), although they probably wrap to a new line. The width that is realistically available for a single name if all three columns are equally wide is something like 210-220px. Now the question is how many characters maximally fit there (and if we want to decrease for example the font size to fit more).

If we cannot show all the characters that we allow for a user name in a single line, we could simply put ".." at the end or probably also wrap them around or simply cut off text that is longer (see comment of chindraba-work above).

**Comment by cellio** [comment]
> If we cannot show all the characters that we allow for a user name in a single line, we could simply put ".." at the end or probably also wrap them around or simply cut off text that is longer (see comment of chindraba-work above).

Yes, this.  It's not realistic to make decisions about how many *characters* a name can contain based on *pixels* -- not with both zoom and unicode/zalgo in play.  I think our limit is 50 characters now, and see the image in the original report.  I think we're much better off enforcing *bounds* and adding "..." if we needed to truncate.  Maybe show the full name in a tooltip on hover.

Maybe on the profile page we can allow the full name if we can wrap it so it doesn't make the whole page too wide.  Anywhere else, though, if the layout constrains rendering a name, enforce the bounds.

**Comment by Trilarion** [comment]
Yes, the current limitation on user names is [3<=length<=5](https://github.com/codidact/qpixel/blob/a0370cd9c0d796eeb992dd202b90656551659beb/app/models/user.rb#L29) but that may be much to much. Maybe we could be a bit more restrictive.

SO seems to limit to 40 characters (length of the field in the database) but actually 95.75% of user names have a length <= 18 characters. And if you concentrate on active users (reputation >= 111) 95.2% have a name length <= 16 characters, so even a limit of say 30 characters would be perfectly reasonable (after all a name is only an identifier and should not distract from the content). See also recent discussion [Codidact's policy regarding posts, user names and profiles with political content ](https://meta.codidact.com/posts/285545).

Question is: Should we additionally to visually restricting the length of the displayed user name in some cases restrict user name lengths further from 50 down to say 40 or 30? If yes, what to do with existing users whose names might be longer (if there are any)?

Are there any existing users on CD with >40 characters in the name? If not, I directly propose that we go down to 40 as part of the solution to this issue here.

**Comment by cellio** [comment]
I don't much care if the limit is 40 or 50.  There are legitimately long names and I don't want to force people into shortened forms, but  if it turns out 40 is enough *and* no one is currently using a longer one, I don't mind dropping it.

As for whether anybody is, we'd need an assist from someone with DB access (Art or luap42).  It feels like work could proceed on setting bounds even without that answer?  Whatever the limit is, it's possible for it to be too long for some places in the UI, so we need to handle that no matter what the limit is.

**Comment by Trilarion** [comment]
I think differently about the length of the user name. On SO 97.6% of all users have a name with <= 20 characters and 99.997% a name with <= 30 characters and 100% <= 40 characters (because that's the limit there).

A name on the Internet shall only be a unique, human readable identifier. 20 characters would be absolutely sufficient for that, 30 characters even in extreme cases and 40 characters are luxury. 50 characters are probably even beyond that and why not more. Why not 100 just to be sure?

The problem is that long names (more in displayed width than character length, but we can only access the latter easily) have a disadvantage. Not only can we not display them fully everywhere (and what is the purpose of a display name that cannot be displayed?), also it takes away space from the content (in comments when referencing to others for example). That's why I think that names <20 characters have an advantage. I'd say that 40 is a more sensible limit than 50.

You're right that the limit could stay and we could just fix the displayed width, but that looks to me like treating symptoms more than causes. That's why I asked the [question elsewhere](https://collab.codidact.org/posts/285625) and if the answer is yes, would also propose to limit the maximal user length to 40 (because what are long user names good for, if we are not going to display them).

**Comment by cellio** [comment]
I have coworkers whose (real, legitimate, would-want-to-use-online) names are >20 characters.  My own name is only 12 characters (13 with the space) and I get annoyed when people call me "Mon" instead of "Monica"; I don't think we should force people to assume nicknames they don't want.  Usernames aren't for treatises but they are for names.  I agree 50 seems like way more than anyone would need, but 20 is too short.

Shortening the username does *not* remove the need to sometimes truncate.  Look at the "name" in the screenshot in the bug report.  You'd have to truncate that at *two* characters.  We're talking about how *often* truncation is needed, not *whether* it is needed.  Also, consider different form factors: the display bounds might be smaller on a phone (or with some zoom) than on a full-screen desktop window at default zoom.

Because we're going to need truncation/bounds-enforcing code anyway, I'd rather separate that from the question of what the character limit should be.  Display bounds are in pixels, not characters.  We might ask on meta what a reasonable character-length limit is and see what the community thinks.

If your name is being truncated everywhere and you *have* a shorter name you're comfortable with, you'll probably adjust it to avoid the truncation.

**Comment by sau226** [comment]
Just as an aside statement, Discourse (which we used for forum.codidact.org) has a name limit of 255 chars - I'm guessing that's because of database type limitations.

Names that are this long are truncated after a certain point - perhaps we can take a look at their implementation as a starting point or to get some ideas?

**Comment by Trilarion** [comment]
With `display:inline-block; width: 175px;` in app/assets/stylesheets/users.scss I can make long user names wrapping to the next line, keep the columns in the users list equal and from overflowing to the right. I did not simply want to make overflow hidden, because that could lead to admin/moderator symbols to be hidden (in case admins/moderators choose long names). It looks for example like 

https://imgur.com/a/83x6iSS

However that would potentially also happen elsewhere, for example in the user cards below the posts, where we may not want it.

One could also simply truncate the displayed name (really show less characters) in app/views/users/_common_card.html.erb but then depending on how long the user names in the other columns are there might not be more than 22 characters visible. And if there are moderator/admin symbols to show even less. Truncating might not be the best idea either.

We could immediately switch to two columns in the users list, if there are users with "long" user names on a page, but that would mean that the layout changes constantly. Probably not good.

I think that wrapping long names to the next line sounds still like the best possibility to me. In this case I maybe want to indicate a maximal width of that element.

Side note: public/assets/community/codegolf.js also accesses card-user--link, so we might check for potential side effects in the end

**Comment by Trilarion** [comment]
I experimented a bit more with this (limiting the width of the user name displayed in the user card, but not cutting it off instead wrapping it around if needed. It looks mostly okay in my eyes.

This is how the post list looks like with very long user names (up to 50 characters) https://imgur.com/a/RlUs6SZ (fits still on a line but such a long user name would definitely clutter the page).

This is how a single post looks like (with the current state) https://imgur.com/a/xQdPmnc (already the user card cannot be on the right side anymore and needs its own row).

This is how the users list looks like with super long user names https://imgur.com/a/7uXwlXz (as posted above only even stronger).

This is how the users list would look like with the changes https://imgur.com/a/qVvfWNm (1-3 lines of user name and all three columns of equal width.

And a post would look like this https://imgur.com/a/0ofXtOk. However there we could wrap at a different width.

Before I make a PR for that, I want to:

Experiment with max-width instead of width (although that should not give an advantage if there are long names in all three columns) and adjust the width to where the user card is used (on the users list smaller than below the card).

It may not be the best possible solution, but will prohibit the users list from overflowing into the right side area.

**Comment by cellio** [comment]
Thanks for working on this.  That looks much better!

**Comment by cellio** [comment]
Closing because the PR was merged (deployment pending).
