### ISSUE TITLE
Allow author to designate a post as "anyone can edit", for canonical posts

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#185]
Requested on meta: https://meta.codidact.com/questions/278386.

We should avoid the term "community wiki", which was sometimes confusing on Some Other platform too.  If we need a name for the type of post that has this designation, we could call it "freely editable" or "shared resource" or something else.

The author of a post should, at creation time or in an edit, be able to designate a post as having this status.  The author shouldn't be able to reverse this setting later, so there should be a suitable warning in the UI.  (We probably want to give mods a way to reverse it, to handle accidents.)

Setting this status should have the following effects:

- The post is labelled somehow in the UI as being freely editable.

- The usercard is changed or replaced in some way.  Maybe it becomes a list of editors like Somewhere Else, or maybe it's a generic symbol (with an informative tooltip) and you can see editors in the history.

- Anybody with the Participate Everywhere ability can edit the post without the edit having to be reviewed.  Users without this ability can suggest edits as usual.

- The post does not contribute to anybody's "post score" computation (for abilities) or reputation.

- MAYBE: change the license type?  I'm not sure what would be suitable here.  At the very least, "attribution" seems murkier with this kind of post.

I propose that the post remain "owned" by the creator -- it shows up on the creator's profile and the creator receives notifications from it.  (Editors, of course, have those edits in their activity.)  We will need to add a check to the computation of post score for abilities, but at least you'd be able to find that thing you remember writing.

**Comment by galegosimpatico** [comment]
[priority: low](https://github.com/codidact/qpixel/labels/priority%3A%20low)?
[complexity: hard](https://github.com/codidact/qpixel/labels/complexity%3A%20hard)?

**Comment by luap42** [comment]
I’m giving this medium priority, because I associate “low” more with “nice to have, but not necessary” and because this feature might be necessary for some communities (for example: Wiki category). 

Complexity is average. Requires mostly some more “cosmetical” than functional UI changes to indicate wiki status and adding a check to every post types UPDATE route, so that we don’t skip to suggesting an edit for users without editing Abilities on wiki posts.

**Comment by cellio** [comment]
I propose that the posts remain owned by the creators rather than fussing with ownerless posts, and updated the description accordingly.

**Comment by ArtOfCode-** [comment]
This doesn't work quite as described here, because doing this as-described would be messy and involve more migrations on the Post table, so... maybe not.

Instead, I've opened the door for communities to request a "Community Resource" post type, which functions as any other post type and could be allowed in specific categories or all categories - still looks much the same other than the post type badge, but can be edited by anyone with the unrestricted ability.

**Comment by cellio** [comment]
Oh, that's cool -- this supports resources and wikis, which is a big help.  The desire to do it for answers is much less frequent, I'd say, and we'll probably want to create a community-proposal type instead of using editable answers for that.  (Need to think that one through more.)

I assume this is a top-level post?  If it's like article but freely editable, is it possible to convert articles to community posts?  (I'm thinking of L&L's resources category.)

**Comment by ArtOfCode-** [comment]
There's no tool for it, but I could do it manually if folks there want all of them to be changed to that.
