### ISSUE TITLE
"Forbidden" ("403") page actually uses HTTP status 401 Unauthorized instead of 403 Forbidden for deleted posts without permission

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#201]
https://meta.codidact.com/questions/277552

> There's a variety of actions which results in a display page saying "403 FORBIDDEN"; for example, accessing a deleted question without sufficient reputation to view deleted questions, including when not signed in.
>
> However, the actual HTTP response code for that, as used in the HTTP response, is not 403, but 401.

See more explanation there.

**Comment by sau226** [comment]
If its OK with the Codidact team, I'd like to work on this issue and see how it goes

**Comment by luap42** [comment]
@sau226 should be okay if you want. 👍 

However, I’m currently working on a larger PR, which will change the use of many of those permission errors (everywhere they are caused of reputation, which is replaced by Abilities). I hope to be able to merge that PR finally within the next two weeks, so if you want to wait until then, that’d be okay too to prevent a huge batch of double-work and merge conflicts. If you want to start now, try to not make too much changes where the permission is denied because of a lack of reputation. 

Also, not sure if you know already, but if you need help or assistance, feel free to join or development chat server: https://discord.gg/7jf8UzS

**Comment by galegosimpatico** [comment]
Maybe it is: https://github.com/codidact/qpixel/blob/4a161f6bd8d5f33aab2a6c8cb86804983ccf26b2/app/controllers/application_controller.rb#L70

In: https://github.com/codidact/qpixel/blob/4a161f6bd8d5f33aab2a6c8cb86804983ccf26b2/app/controllers/application_controller.rb#L67-L74

**Comment by sau226** [comment]
Thanks for the pointers - I have linked a PR that I hope will resolve this issue.
