### ISSUE TITLE
Comments ending with RTL text can mangle username/date text that follows

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#212]
https://meta.codidact.com/questions/278004

Example:

![Screen Shot 2020-10-22 at 7 54 24 PM](https://user-images.githubusercontent.com/5557942/96941437-6a8ed300-14a0-11eb-9e08-d2c6dcb298dd.png)

In a comment two weeks ago I said I could no longer reproduce.  Someone else reported it still happening, and when I looked tonight I see it (again? still?).

**Comment by ArtOfCode-** [comment]
If there was a `complexity: PITA` tag I'd add it...

**Comment by galegosimpatico** [comment]
it's not pita.. find a way to reproduce eventually, and surely a chain of directional pops at the end of each string will sweep whatever it is as easy as it did with rtl overrides!

**Comment by ArtOfCode-** [comment]
Repro here if you want it, @galegosimpatico - https://languages.codidact.com/questions/277278#answer-277334

**Comment by galegosimpatico** [comment]
I typed "a way to reproduce". A reproduction doesn't help me with this one, because my approach is to have markup and code leaving server with the directional pop chains already set up.

**Comment by ArtOfCode-** [comment]
Not quite sure what you need, @galegosimpatico - I can get you the raw text of that comment from the database if you need it, or..?

**Comment by galegosimpatico** [comment]
The UTF-8 bytes would do, but I don't know how to extract them from the database. When I selected a field with RTL overrides in the database, in my shell console, I think it just printed some replacement character. I only manipulated the UTF-8 bytes by getting them at the Ruby level from the text as returned by the database.

The string, enclosed in some delimiters, might do, but I'm not sure. And because I suck so much at RTL languages themselves, reading the reproduction you linked I don't know what I would need to copy in order to reproduce. Not feeling like figuring out by just doing random trials.

So I was hoping maybe the comment's author can be told to explain how to reproduce, fools proof. But maybe it can't be done. In the end it might need a developer actually user of RTL languages. I don't know. The past RTL overrides issue, on the contrary, it didn't really involve no text written in no RTL language. The reproduction guide was pretty clear then: write some characters, paste an RTL override character, write some more characters, maybe paste some other directional character, etc., that's the kind of steps I can follow.

**Comment by ArtOfCode-** [comment]
The UTF-8 bytes in the comment:

```
54 68 65 20 71 75 65 73 74 69 6F 6E 20 77 61 73 20 61 62 6F 75 74 20 5E8 5DB 5D1 20 76 65 72 73 75 73 20 5D0 5D5 5D8 5D5 2C 20 6E 6F 74 20 5E8 5DB 5D1 20 76 65 72 73 75 73 20 5DE 5DB 5D5 5E0 5D9 5EA 2E 0A 20 20
```

The raw content:

```
The question was about רכב versus אוטו, not רכב versus מכונית.
  
```

**Comment by galegosimpatico** [comment]
Good, good.

Doesn't let me reproduce exactly what seen in [OP's][3] [screenshot][4] (also [here][5]) (nor I'm going to be able to, because I see [this][1] in Codidact, but consistent with [what I locally see in qpixel][2] with the text you shared), but it doesn't render correctly anyway, so it's anyway showing something to be fixed.

I think the user's name doesn't feature directional manipulation. But just to make sure, `mysql> SELECT username FROM users WHERE id = 8106;` ([msh210][0])?

[0]: https://languages.codidact.com/users/8106
[1]: https://frupic.frubar.net/40911
[2]: https://frupic.frubar.net/40912
[3]: https://meta.codidact.com/questions/278004
[4]: https://s3.amazonaws.com/storage.qpixel.artofcode.co.uk/KKwikHQvpKdPw2mmvuZtJSat
[5]: https://user-images.githubusercontent.com/5557942/96941437-6a8ed300-14a0-11eb-9e08-d2c6dcb298dd.png

**Comment by galegosimpatico** [comment]
Note: it's Safari that has to be used to reproduce the bug in its full unfolding: as just seen in [codidact.com][0] (and [reproduces locally][1] easily).

[0]: https://frupic.frubar.net/40914
[1]: https://frupic.frubar.net/40913

**Comment by galegosimpatico** [comment]
Remember this bug manifests differently not only depending on the browser used, but also depending on whether the `about` text pops out or not.

**Comment by galegosimpatico** [comment]
Good.

Hardwiring a single directional pop right after [the comment text][0] wasn't immediately helpful, I don't understand why.

However, enclosing [the comment text (the single "line 5 in 836bfb2")][0] in a `<span dir="ltr">` taken from how you fixed the username [here][1] and [here][2] seems fixing here too, fixing all my four cases with/without `about` and using Opera or Safari. Of course that's going to break when the site is l10n in RTL languages, but because you wrote [that's off scope][3], it should to be good enough.

---

Line in source code for comment text: https://github.com/codidact/qpixel/blob/836bfb23223268fa61b0e60b82714758a1c60ed3/app/views/comments/_comment.html.erb#L5

[0]: http://github.com/codidact/qpixel/blob/836bfb23223268fa61b0e60b82714758a1c60ed3/app/views/comments/_comment.html.erb#L5

[1]: http://github.com/codidact/qpixel/commit/231d547eba13a

[2]: http://github.com/codidact/qpixel/commit/ec7cb05a19000a70c709452811d0c6ea19f36e5a

[3]: https://github.com/codidact/qpixel/pull/220#discussion_r511400378

**Comment by ArtOfCode-** [comment]
Thanks for looking into this, @galegosimpatico - that commit above does as you suggest, wrapping it in a `dir="ltr"` - we'll see if that fixes things.

**Comment by MoshiKoi** [comment]
No longer relevant due to the threads update
