### ISSUE TITLE
Hebrew usernames are backwards

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#234]
https://judaism.codidact.com/questions/278167

Hebrew usernames are rendered backwards.  This is a regression that was introduced a month or so ago; there's some speculation on the linked question but I don't know how accurate it is.  As a concrete example, see https://judaism.codidact.com/users/53026, whose name is רבות מחשבות not ‭רבות מחשבות‭ (the latter is nonsense).  While a user can apparently work around it by adding explicit RTL/LTR directives in the name, people shouldn't have to do that.  We have a Judaism community, where Hebrew names will occur more often than in the general public.

I'm setting priority as medium because it's not a blocker or something that affects a lot of people, but the people it does affect are affected pretty badly and it makes one of our communities look kind of stupid, so it'd be great if we could fix this.

**Comment by galegosimpatico** [comment]
Bug goes away by removing the first/left LTR override character added in `rtl_safe_username`.

That was added by https://github.com/codidact/qpixel/commit/a624079f8cafce185a42bcf3e4f1a1ea8c9e80d8 for https://github.com/codidact/qpixel/issues/136, but because that's an "artificial" bug and this is a legitimate bug, let's promptly remove the offending LTR override character, and if anything breaks, fix it using [רבות מחשבות](https://judaism.codidact.com/users/53026) as a boundary constraint for such bug.

---

https://github.com/codidact/qpixel/blob/88475cb3b7236df996c71e6f3b9bf6811ee6936d/app/models/user.rb#L103-L105

**Comment by cellio** [comment]
@galegosimpatico you're saying complexity:easy (and we can prevent the previous bug from recurring)?

**Comment by galegosimpatico** [comment]
Yes, I think this bug just vanishes.

About the previous bug https://github.com/codidact/qpixel/issues/136, I don't know if there's anyone using RTL overrides in their names currently, but I doubt it affects.

I think the first/left LTR override of `rtl_safe_username` is for enforcing an LTR rule for LTR usernames when the page is showing in localized RTL. That can't happen because the site isn't localized.

I think it shouldn't interfer with https://github.com/codidact/qpixel/issues/212 either because that one's about the characters following in stream the LTR override that would remain in place.

**Comment by galegosimpatico** [comment]
LTR developer note: If you browse the data from console, RTL rules until stopped:

```
mysql> SELECT username, id, created_at FROM users WHERE id in (12, 14, 15);
+-----------------------+----+---------------------+
| username              | id | created_at          |
+-----------------------+----+---------------------+
| qpixel                | 12 | 2020-08-24 07:36:24 |
| qpixel1               | 14 | 2020-09-13 10:19:03 |
| רבות מחשבות           | 15 | 2020-10-26 14:41:39 |
+-----------------------+----+---------------------+
3 rows in set (0.00 sec)

mysql> _
```

There'll be a more elegant to reset direction there, but appending "some LTR text" makes that text's direction rule on the previous change of direction done by the name:

```
mysql> SELECT CONCAT(username, '_ltr'), id, created_at FROM users WHERE id in (12, 14, 15);
+---------------------------+----+---------------------+
| CONCAT(username, '_ltr')  | id | created_at          |
+---------------------------+----+---------------------+
| qpixel_ltr                | 12 | 2020-08-24 07:36:24 |
| qpixel1_ltr               | 14 | 2020-09-13 10:19:03 |
| רבות מחשבות_ltr           | 15 | 2020-10-26 14:41:39 |
+---------------------------+----+---------------------+
3 rows in set (0.00 sec)

mysql> _
```

**Comment by galegosimpatico** [comment]
Displaying [רבות מחשבות](https://judaism.codidact.com/users/53026) is fixed!
