### ISSUE TITLE
Markdown tries to apply block-level styling to comments, losing content

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#253]
https://meta.codidact.com/questions/278611 is a bug report about comments that begin with "1. " -- the number and period disappear.  In comments, @luap42 says it's a more general problem with Markdown that looks like it's for block elements:

> Furthermore, it appears that the issue isn't specifically with numbers followed by a dot but by everything that can cause Markdown to produce something (lists, headings, quotes, ...). The HTML is sanitized differently for comments, but Markdown doesn't know that and hence produces a list/header/comment.  The sanitizer then removes the <blockquote> tag and hence it looks like the number (or dash or #) was removed. I think the right solution would be to make the Markdown generator know that we are in "inline Markdown" mode and hence not generate block-level stuff. — ‭luap42 is a ghost 👻 ‭ 14 days ago

**Comment by trichoplax** [comment]
Consider in parallel with https://github.com/codidact/qpixel/issues/941

**Comment by trichoplax** [comment]
This appears to be fixed by #1065 that fixed #941.

I've tested this in my development environment and both numbered lists and bullet point lists work find in comments now. I haven't flagged the Meta post to be marked as status completed as the fix hasn't been deployed live yet. Adding this comment as a note that this can be closed after the next deploy.

**Comment by trichoplax** [comment]
Tested in live. Blockquotes, numbered lists, bullet point lists, and bullet points inside blockquotes all work perfectly in comments.
