### ISSUE TITLE
Running rails db:seed during dev environment does not seed a community

### ISSUE THREAD

**Issue by sarahmccuan** [codidact/qpixel#28]
When setting up an initial development environment following the instructions given on the front page, no community is created when running rails db:seed. This causes a 500 error when starting the server as no community can be loaded. 

![image](https://user-images.githubusercontent.com/35535105/78740507-fb4afa80-7924-11ea-9e39-75169219d568.png)

![image](https://user-images.githubusercontent.com/35535105/78740582-2d5c5c80-7925-11ea-8b0e-cc8599e9294f.png)

**Comment by sarahmccuan** [comment]
Note: The 500 error can be bypassed by commenting out the following line in app/controllers/application_controller.rb. `    Rails.logger.info "  Host #{host_name}, community #{RequestContext.community_id} (#{RequestContext.community.name})"
`

**Comment by ArtOfCode-** [comment]
Good catch. We can add a community seed easily enough. We should probably _not_ bypass that error by default, though: we could change the log to `RequestContext.community&.name || '(no community)'`, but we should _also_ add a check in `ApplicationController#set_globals` or similar to make sure there is a community present, otherwise the lack of data will confuse people. Might be worth adding an error view that we can render when there's no community.
