### ISSUE TITLE
In post editor, add button for "insert table"

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#313]
https://meta.codidact.com/questions/279511

Markdown table support is fairly recent I think, which is great.  People don't always remember how to do it.  Plus we have buttons for other Markdown assists (bold, links, etc).  This request is to add a button for "insert table".  We don't want to get into the hassles of a UI for specifying the number of rows or columns; I think it's enough if it inserts a template that you have to then edit.  Two columns, headers, and two rows would be fine, or pick something else that makes more sense if something does.

**Comment by fedorqui** [comment]
I assume it consist in adding a `table` item in

https://github.com/codidact/qpixel/blob/aaab87b30b525d9486426de7c7af92ae7fdfea98/app/assets/javascripts/markdown.js#L24

```
const actions = {
      bold: ['**', '**'],
      // 
      hr: ['\n\n-----\n\n', null],
      table: ['| Title1 | Title2 |\n|- | - |\n| row1_1 | row1_2 |', null]
    };
```

And then in https://github.com/codidact/qpixel/blob/817875927153f55547cc5fed4d47e939e41eb2a2/app/views/shared/_markdown_tools.html.erb#L60 adding a line like:

```
    <%= md_button action: 'table', label: 'Table', class: 'is-icon-only' do %>
      <i class="fas fa-fw fa-table"></i>
    <% end %>
```

Not sending a PR because I may be missing something.

**Comment by ArtOfCode-** [comment]
Spot on, @fedorqui, if you want to PR that I'll happily merge it :)

**Comment by fedorqui** [comment]
Done in #317 :)
