### ISSUE TITLE
Send notification if ping edited into a comment

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#319]
https://meta.codidact.com/questions/277321

The meta question has a "status-planned" tag, added a couple months ago, but I can't find a trace of it in GitHub, so creating this now. 

> Sometimes, I forget to mention someone when I first make a comment, and I go and edit the mention in. However, I've been told that this doesn't actually send them a notification. Can we get it so that it does?

(Confirmed by reporter as not working as of 2020-10-26.)

**Comment by Taeir** [comment]
This sounded simple, but turned out to be a bit more tricky and expansive a feature.

Often, someone who is pingable in a comment also follows the thread (because they commented probably). The ping notification takes precedence, so if you are pinged you get that one rather than the follow notification.

When you retroactively add a ping, we have to deal with the fact that we could now be sending a second notification for a comment. What should the behavior be here?

**Comment by cellio** [comment]
Oh, good question.  It's possible we didn't have thread-following when this was first raised on meta.

At edit time, can we check if the person is already following and not notify for the ping if so?  I realize that "you were mentioned in a comment" is a higher priority to the reader than "there's a new comment in a thread you're following", but I don't think we want to go down the path of trying to retract the first notification and replace it -- that feels like trouble if the user already has it open or opens at _just_ the wrong time or something.  I'd rather withhold the second notification than try to edit history.

Would that be too complicated?  If so, we should discuss whether a double ping is too annoying or just something to live with.

**Comment by Taeir** [comment]
Implemented the withholding behavior.
