### ISSUE TITLE
Cross-community promotion (done responsibly)

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#352]
We've had requests for something like Somewhere Else's "hot" list, both from people who want to consume it and from people who want to use it for cross-community promotion on our network.  It makes sense -- if you already participate on one Codidact community, the odds are higher than in the general population that you'd participate on another, if only you saw something that told or reminded you that it exists.

We've seen a lot of problems when an algorithm attempts to pick questions to advertise, though.  Let's not go there.

Let's allow communities (maybe curators in addition to moderators?) to *nominate* posts for broader network advertisement.  We would then use our own ad server to (sometimes)[^1] generate an ad to show in the right column, below the featured posts and above the local hot posts.  The post for the ad would be chosen randomly from the pool of posts that have been nominated across the network.   (It's ok if, for performance reasons, we can't exclude the local community.  Heck, it might even be good for people to occasionally see "their" stuff on that list.)  Consider adding a link below the ad that goes to a list of all currently-nominated posts, for people who want something more like the "hot list" instead of one post at a time.

To keep the list fresh, I suggest we expire a candidate after some amount of time (maybe a couple weeks?).  If the community wants to nominate it again they can.

[^1]: "Ad blindness" is a thing; we don't want to *always* show an ad.  I don't know what the right randomness factor is.  As for where, I'd say post lists for sure and probably individual posts, but not other places.

**Comment by manassehkatz** [comment]
Agree with the perceived end result. Disagree about the *technical* methods. Specifically, while conceptually these are "ads", there are two important ways in which I don't think they should be "ads" of the nature of ads of unrelated items on a site:

1 - This should all be done within the core code. Many ads are done using Google or other APIs via Javascript that loads a 3rd-party ad. That is not inherently evil, but it is unnecessary when dealing with our *own* communities and doing so would also likely trigger AdBlockPlus and other "ad blocking" technologies (and for very good reasons!). So while we may think of it as "ad from one community on another's page", really this should all be one system. That might change a little if/when we split things up so that different communities are on different servers - or more importantly, separate databases - but even then, there are ways to put all the "ads" into one database and serve them through the core code to all communities as needed.

2 - While in some ways these promotional links should stand out a bit, much like ads in general, since they are all part of the one system, they can really be an expansion/enhancement of the current "Hot Posts" sidebar.

Additional things to consider:

* I like the idea of people besides moderators being able to "nominate" a post. But let moderators add/remove at their discretion (within specific community guidelines) and (in an emergency) system-wide admins/staff remove.
* Some automation may be useful. For example, if a post is Closed due to some non-moderator process (not even sure how that works currently, but SomeplaceElse if 'x' people Close, the post is Closed), the post should be automatically removed from the "ad" list. Similar if Author deletes. These can be handled either as a side-effect of the Close/Delete or as a part of the query that selects the next active "ad".
* Including or excluding the local community for which posts are included as possible ads to be shown should be trivial.

**Comment by cellio** [comment]
On your first point, I meant using our *own* ad server, the one that produces [these templates](https://meta.codidact.com/ca).  I assume that's in the qpixel code, since the link is shown in the right column on our communities.  I'm not talking about anything from outside the network.

I originally proposed this as a list of links (so there'd be several posts shown, max configurable by the community), but as I was writing it I kept thinking of our own ad server and also that we've got a lot of text in that column already.  Initially the number of such posts will probably be small (few communities, few nominations per), and if people keep seeing the same basic list they'll tune it out.  That's why I proposed one at a time along with making the full list available via a link for those who want it.

Good point about mod/admin overrides, and about dropping posts under some conditions. I agree.  (Note that the posts could include more than questions, so "closed" logic needs to be specific to questions.)

**Comment by manassehkatz** [comment]
I know it is our "own" ad server. My point is that it should be served "just like the rest of the page", not as a almost-like-it-is-from-elsewhere link/snippet of code, as those types of things tend to trigger ad blockers and are also a little harder to maintain than standard server-generated pages.

"Closed" or "Deleted" could potentially be any type of post - someone starts writing an "Article", moderator likes it and makes it "Hot", author decides based on feedback to take it "offline" for a while to rewrite it.

**Comment by ArtOfCode-** [comment]
Shouldn't be too difficult to do. Our ads don't tend to get blocked as ads, fortunately... yet, at least.

**Comment by manassehkatz** [comment]
What I am suggesting is that *when used internally* the "ads" should be served as page elements - i.e., directly with the rest of the page content, not loaded via Javascript, AJAX, API, etc. as many "ad servers" do. That is not generally an option if our ads are being served on unrelated sites, but for our own "network" should work just fine and totally avoid "ad blocker" problems.

**Comment by cellio** [comment]
Oh, I get what you're saying now.  Yeah, I don't much care how the "ads" get there; if we can take a shortcut to get the image, since we control both ends of the connection, that sounds fine.  I leave assessing that to the folks who know how the code works. :-)

**Comment by ArtOfCode-** [comment]
Yep, that's perfectly possible, we can just include them directly as images.

**Comment by ArtOfCode-** [comment]
And done
