### ISSUE TITLE
Please investigate: edits made and recorded in history but not applied

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#369]
https://meta.codidact.com/posts/279889 reports an edit that was made, shows in the history, and isn't reflected in the post.  This edit occurred during the db-upgrade window with the abilities change.  This specific case has been resolved, but we don't know if there are other cases.  Is there any way to query for these, to at least know what posts to go look at by hand, if better methods aren't available?  This is as much a matter of instilling confidence that we didn't lose anything as it is about specific edits.

**Comment by ArtOfCode-** [comment]
I looked at this at the time: we concluded that there's a small number of affected posts, but (a) there's no way to fix them without manual involvement because the diffs have diverged, and (b) we haven't lost any data, it's all there in post history &mdash; so we left it up to post authors/editors whether they wanted to update posts or not.

**Comment by cellio** [comment]
Oh, I'm sorry!  When I came across the meta post again last night, and didn't find an issue about it, I was afraid I had dropped a ball.  I wasn't looking in the right places.
