### ISSUE TITLE
Data import created duplicate entries with different answer counts

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#39]
From the Outdoors front page:

![Screen Shot 2020-04-26 at 11 10 21 PM](https://user-images.githubusercontent.com/5557942/80330498-4fa21580-8813-11ea-9c51-54d1812a6474.png)

The first of the two links to https://outdoors.codidact.com/questions/46971, which has 0 answers (not 3).

The second links to https://outdoors.codidact.com/questions/41874, which has 3 answers (not 0).

I noticed and reported duplicates (in Discord) about a day ago.  The examples I found then had different answer counts on the question list and different URLs, but they both had all the answers when I clicked through.  I don't know if this means there are two separate problems, or if fixing that caused this somehow.  I don't have the previous examples handy, sorry.

**Comment by ArtOfCode-** [comment]
This is a bit of a pain, but it's ultimately caused by the wacky import process I used for Outdoors. There's an item on the TODO list about making imports stable again which I'm planning to look into soon, which should eliminate this.

There's no easy way of cleaning up the duplicates, annoyingly. I can run some queries to correct the answer counts so that they show the correct number of answers on the front page, but identifying and removing the duplicates is difficult.

**Comment by cellio** [comment]
Thanks for the explanation.  Ok, we can delete dupes as we come across them, and the import changes should prevent a recurrence with the next community.  Good enough.

**Comment by cellio** [comment]
Also reported by a user here: https://outdoors.codidact.com/questions/74785
