### ISSUE TITLE
New lines have different formatting between preview and post

### ISSUE THREAD

**Issue by sarahmccuan** [codidact/qpixel#41]
In the answer preview a single newline shows up as a full newline. Once I post, however, that newline is lost. Not sure which behavior is intended, but we should be consistent.

**Text**
![preview](https://user-images.githubusercontent.com/35535105/80413186-0eeede80-889d-11ea-8723-3b452730aac8.PNG)

**Preview**
![previewed](https://user-images.githubusercontent.com/35535105/80413193-11513880-889d-11ea-9ff3-2e951ac075f3.PNG)

**Actual post**
![answer](https://user-images.githubusercontent.com/35535105/80413196-13b39280-889d-11ea-8898-bc39440228c4.PNG)

**Comment by ArtOfCode-** [comment]
The latter is intended, because that's the Markdown standard - if you want a single line break, you need two spaces at the end of the previous line. This difference is there because the preview renderer is a JS library, while the server-side render is done by a different Ruby library. I'll have to look at whether the JS can be configured to avoid that.

**Comment by cellio** [comment]
I've noticed other differences between preview and final rendering (blockquotes, something about list formatting but I don't recall what, superscripts).  Is it possible to (eventually) use the same library in both places?

**Comment by ArtOfCode-** [comment]
It's not possible to use the _same_ library - one is client-side JS, the other is server-side Ruby. It's probably possible to configure them both to do the same thing, though.
