### ISSUE TITLE
Confirmation link uses the meta.codidact.com domain, not the actual site domain

### ISSUE THREAD

**Issue by MoshiKoi** [codidact/qpixel#427]
I recently created an account on the dev server, and it sent me an email with a link to confirm my account. However, the link used the meta.codidact.com domain, not the domain of the site I actually signed up for (a.dev.codidact.org). This means that the link didn't work, I had to edit the link manually to change the domain.

**Comment by cellio** [comment]
We've been treating this as a low-priority annoyance so far, on the theory that the small number of folks on the team can edit the URL to bypass it, but we'll need to fix this for others to be able to run instances.

**Comment by sau226** [comment]
This just requires a mailer patch, however I'm not sure what we want to set it to/how to do so in an instance neutral way.

Everything is hardcoded in the instance mailer config (example: https://github.com/codidact/qpixel/blob/develop/config/environments/production.rb#L83) in case anyone wants to take a shot at this.

**Comment by cellio** [comment]
Ideally, this would be set in a parameter somewhere and default to something like YOU.EXAMPLE.COM.

**Comment by ArtOfCode-** [comment]
This is configurable for folks running their own, just needs the value changed in the mailer configuration. Not so easy to make it use the same site as the user registered on, but we could look

**Comment by cellio** [comment]
Sounds good to me @ArtOfCode- -- maybe we could do this on the dev server to validate the approach and then just document it somewhere?

**Comment by sau226** [comment]
The link has been overridden on the dev server to point to the faux Codidact Meta hosted there, by varying the meta references in the file linked above.

**Comment by cellio** [comment]
Great.  Can we add some developer doc (maybe in the setup instructions in the GH readme?) about where to change this for your instance?

I think it'd be good if the base version, the code in the repository that people can install and set up, used a placeholder that people have to edit, instead of using our URL by default.  Can we change that (if we haven't already)?  It won't affect our instances, which are already customized, but it would affect the next fresh install.  example.com exists for things like this; it's safe and won't ever redirect to somebody real.
