### ISSUE TITLE
Sort by age no longer works

### ISSUE THREAD

**Issue by MoshiKoi** [codidact/qpixel#659]
Sorting by age no longer works properly. See for example https://codegolf.codidact.com/posts/279147?sort=age, where sometimes newer posts will be shown out of order for some reason. (E.g. there was a 10mo post, then a 7mo post, then another 10mo post).

**Comment by Istiakshovon** [comment]
Are you sure? You are using correct link. Cause, when I hover on `active` tab then, it was showing `?sort=active`rather than `?sort=age` even, I can't find anything called `age` for answer sorting.

**Comment by cellio** [comment]
`?sort=age` isn't a valid option, and so the page is showing you the default view instead of emitting an error.  If you look at the buttons above the answers, you'll see that neither "score" nor "activity" is highlighted, since you didn't choose either of those.  If you go to the page without the sort option, you'll see them sorted by score and score will be selected.  You get the same behavior for any invalid sort option, like https://codegolf.codidact.com/posts/279147?sort=codidact-is-awesome .

**Comment by MoshiKoi** [comment]
@cellio I see. I was just confused since sorting by age *used to work*, though it seems like it was unintended.

**Comment by cellio** [comment]
There used to be a bug when sorting by what was labeled as "activity" actually sorted by age.  I don't know if the URL was wrong or just the behavior.  That might be what you were remembering.
