### ISSUE TITLE
Dropdown isn't showing when you aren't logged in

### ISSUE THREAD

**Issue by Istiakshovon** [codidact/qpixel#691]
Steps :

- Log out
- Click on Community's list dropdown

I am using Google Chrome

![image](https://user-images.githubusercontent.com/58106197/137427930-8e9864bf-5e69-40e3-b0b7-611296c07cfb.png)

**It's only happening in Writing CD.** In [the post](https://writing.codidact.com/posts/284237). It's working fine everywhere else.

**Comment by MoshiKoi** [comment]
This is the issue:

![image](https://user-images.githubusercontent.com/54333972/137541451-cef75656-c203-4d39-bef3-b69a3330dbe6.png)

> Uncaught Missing target for DropPanel: #post-284362-reactions-panel

I think the cause is that we are not giving the reactions panel when the user is logged out, but we still have the react button, and so it cannot connect the button to the panel.

Basically, remove the react button when the user is logged out and can't use it anyway, or make the react panel available

**Comment by sau226** [comment]
I added a PR to remove the button pending a proper fix of its error handling for logged out users
