### ISSUE TITLE
Extra whitespace around titles hinders copy/paste

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#701]
https://meta.codidact.com/posts/284083

Copying the title of a post adds an extra space at the end in Firefox.  Apparently Chrome swallows it, but the space is there in the HTML.  This means if you try to add a friendly link to another question by copying the title into Markdown, you have to go back and delete the space.

A comment there says:

> I'm getting the behavior that OP is describing, running Firefox 78.14.0esr. Simply triple-clicking the question title on the question page is sufficient to demonstrate this for me; a copy and paste into a plain text editor further confirms it. A quick look at the actual HTML source code of the page also reveals *massive* amounts of whitespace around the question title, both in the `<title>` element within `<head>`, and within the `<h1 class="post-title ..."><span class="post--title-text">` within the document body. Since HTML is non-whitespace-sensitive, multiple whitespace would typically be compressed into a single whitespace character, *but* that single whitespace character *is* significant as a word separator.

**Comment by cellio** [comment]
I don't know if the issue is in the front end or if the extra space is being added to the title in the database.  I've labelled it for the front end for now; please adjust as needed.

**Comment by MoshiKoi** [comment]
It seems to be due to the fact that the source has indentation and other whitespace:

https://github.com/codidact/qpixel/blob/260f598caf31c091bbffb18b041ccd9533c2a73a/app/views/posts/_expanded.html.erb#L16-L20

You can see that the line breaks are being transferred to the source as well, for example with [this post with a duplicate notice](https://meta.codidact.com/posts/279015):

![inspect element shows line breaks in source](https://user-images.githubusercontent.com/54333972/140865358-8efc8fa8-cfd3-41a9-8a95-0990c73eb6ab.png)

I'm not familiar with erb templates, so I wouldn't know how to fix this other than removing the code formatting, which makes the code less readable.

**Comment by ArtOfCode-** [comment]
There is no way to fix this without removing the formatting in the code, which just makes that code a nightmare for readability. I think we have to decline this one - the impact of having to delete a single space is pretty small, whereas the impact it would have on the code is significant.

**Comment by JesseWeinstein** [comment]
I think this would remove the space and (IMO) still be readable. I may be wrong (about either or both of those), though!

```
<span class="post--title-text"><%= 
         post.title %><%=
         post_type.is_closeable && post.closed && !post.duplicate_post ? " [closed]" : "" %><%=
         post.duplicate_post && post_type.is_closeable && post.closed ? " [duplicate]" : "" 
       %></span> 
```

**Comment by cellio** [comment]
@ArtOfCode- any thoughts on that?  (I didn't know if you'd get pinged by that comment, so just making sure.)

**Comment by mbomb007** [comment]
Would the problem still occur if the template used tabs instead of spaces?
