### ISSUE TITLE
Can we remove SE's Amazon affiliate links?

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#71]
It was pointed out to me in a tweet (https://twitter.com/jlericson/status/1257726563304435714) that Amazon links that get posted to SE get turned into affiliate links that benefit SE.  That's fine for content they host, but is it feasible to sanitize those links on *our* sites?  If so there are two pieces: fixing links we already have (example in https://outdoors.codidact.com/a/46124/46134) and catching them when importing data.

**Comment by manassehkatz** [comment]
Definitely want to fix this! No point sending affiliate $ to SE. Fortunately, it looks like they use a simplistic URL replacement instead of running it through a database/hashing/etc. So:
http://rads.stackoverflow.com/amzn/click/B004PPNSGY
changes to:
https://www.amazon.com/dp/B004PPNSGY
Which means simple: Replace **http://rads.stackoverflow.com/amazn/click/** with **https://www.amazon.com/dp/**
I see no reason that couldn't be done as a one-off global search/replace through the existing posts and then added as a step in the import process.

**Comment by ArtOfCode-** [comment]
Done for existing links, leaving this issue open to remind me to do it in data import.

**Comment by cellio** [comment]
Marking deferred because we're not working on bulk import right now, but also marking easy based on the comments.  If we do single-question import (a different feature request) we'd want to do it there.

**Comment by trichoplax** [comment]
Is data import still a thing (either in bulk or for a single question)? If not, is this ready to be closed?
