### ISSUE TITLE
Having two different symbols for moderators is confusing

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#816]
https://meta.codidact.com/posts/286545

The symbol we show next to a user name for moderators is configurable (any Unicode symbol).  It's not the same as the icon on the user profile in the right column, above the abilities list; that one is baked into the code (I believe).  Can we use the same symbol for mods everywhere?

**Comment by Taeir** [comment]
Does this look okay? (Testing with different shield emoji than shown in the meta post).
![image](https://user-images.githubusercontent.com/668952/185432302-0d8d56a4-7ab4-4c15-ae43-d44af29df90a.png)

Otherwise, it becomes very hard to see if we remove the blue box:
![image](https://user-images.githubusercontent.com/668952/185432628-e9d3fd43-e564-4603-bf07-730ff5f4cf12.png)

**Comment by cellio** [comment]
I agree on the background for legibility.

Are you pulling the symbol from the configuration now, or baking in the new shield (which is correct now, but if anyone changes it we'd be back to the confusing difference).

**Comment by Taeir** [comment]
I'm pulling from the site configuration now. I set the Unicode shield as the emoji (this is how my browser renders it)

The old icon used is from the fontawesome icon set, called shield.

**Comment by luap42** [comment]
OTOH if we are going to unify this, I'd rather advocate for using the shield everywhere. Even in the version with the blue background, the text icon is barely readable in the screenshot in the issue IMO. Also, I think a shield might be a better representation of the moderator concept than a thin pentagon.

**Comment by Taeir** [comment]
The problem with the configuration item is that it asks for a character (or characters) to use. We can also use the icon from the fontawesome set always, but then we lose the configurability.
Another option is to allow the site to set the full html (similar to how things like guidance for posting are configured). That way both are possible, but the complexity of configuring it goes up (if you put the wrong thing in there it essentially breaks rendering of all user cards.
Perhaps we could use the fontawesome shield in case it is blank, and the character if it is specified otherwise?

**Comment by cellio** [comment]
On the Admin page, under Site Settings, you can set the icons for staff and mod.  Those currently, IIUC, require a fontawesome character.  I gather that the icon used in this PR is a graphic and not a fontawesome character?

Can we make it so that, in Site Settings, you specify a *thing* and we use it in both usercards and the profile?  What's a *thing*?  Fontawesome character for backward compatibility or (maybe) path to an icon image file to upload, or if that's too hard, bake in some choices?  I don't know enough about how this is currently set up to have opinions on implementation, but from the user perspective, it would be nice if it could be set in one place.  If that means two settings and text that says which one takes priority if you do both, that's fine.  What do you think is practical and minimally confusing, @luap42 ?

**Comment by ArtOfCode-** [comment]
IIRC the site setting currently just asks you to put _any_ character in to use as a moderator symbol. We could update that to allow free choice of a FontAwesome icon, which gives good choice and consistent rendering - then we just need to make its use consistent across the site.

**Comment by Taeir** [comment]
I updated it to be a fontawesome icon instead.
