### ISSUE TITLE
New release? 0.7.1/0.8.0

### ISSUE THREAD

**Issue by frafra** [codidact/qpixel#891]
Latest release is almost 2 years old: https://github.com/codidact/qpixel/releases
I was wondering if it is the development of the software is stagnant, or if it would make sense to have a new release.

**Comment by ArtOfCode-** [comment]
Development hasn't stalled, we just haven't actually made a release in a while. Current progress is on the develop branch.

**Comment by cellio** [comment]
I've been thinking for a while that we ought to make a release, too.  Is it hard?  Are there any barriers?

**Comment by not-a-ethan** [comment]
@cellio 0 barriers. You can do it all through the GH UI. [Release docs](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases)

**Comment by frafra** [comment]
> Current progress is on the develop branch.

What about dropping master if it is unused?

> The one problem is that since we already made the commits they will all be in 1 release.

You can also decide to recap the most notable changes without having to list a huge list of merges or commits.

**Comment by cellio** [comment]
It looks like releases can be designated at any commit, not just the current one.  (If I'm understanding this correctly.)  @ArtOfCode- , I think "version running on our network now" (which is six months back) and "version the new university deployment took" would be reasonable version bumps.  Then when much of the current work lands, there'd be enough changes to justify another bump.  What do you think?  Since `master` is what people see when they visit, I think it's good to show some more recent activity -- through version bumps or pushes to master or something else I haven't thought of.

**Comment by ArtOfCode-** [comment]
0.8 published.
