### ISSUE TITLE
Admin profile editing

### ISSUE THREAD

**Issue by ArtOfCode-** [codidact/qpixel#9]
Admins (not moderators) should be able to edit profiles on behalf of any other user.

**Comment by cellio** [comment]
With https://github.com/codidact/qpixel/pull/1009, moderators will be able to reset (not otherwise edit) user names and profile "about" blocks.  I think that meets the spirit of this request for now; if we need more fine-grained admin editing we can reopen, but that probably means having history and diffs and stuff, so... more complicated.
