### ISSUE TITLE
Regression: tools menu on comment thread pages does not open

### ISSUE THREAD

**Issue by cellio** [codidact/qpixel#960]
The "tools" menu on comment threads holds some important moderation actions, including freezing and deleting.  This menu is currently inaccessible in prod -- clicking on the link does nothing.  The console shows several 404s ("failed to load resource"):

![screenshot](https://user-images.githubusercontent.com/5557942/212944772-b545d999-ea52-4e40-a321-412cd749e8e5.png)

I don't know enough about console-based debugging to extract more information, but I'm happy to follow instructions if I can help.

**Comment by trichoplax** [comment]
It looks like those errors in the Console are red herrings. The first two are the 404s for the custom CSS and JS, which should change to 204s after the next release and no longer show on the console. The more unnecessary errors we can get rid of, the less distractions we'll have when trying to tell what has really gone wrong.

I haven't yet been able to tell what the underlying cause is (there doesn't seem to be a way of clicking around the edge like there is for the problem with the buttons at the top right of the page). However, I do have a horrible workaround if you have something urgent enough to justify using it. The tools menu is still fully functional, it's just invisible, and you can force it to become visible using the developer window. I've downloaded Chromium which should hopefully mean the following images look more or less the same as they will for you in Chrome:

![Page and developer window before removing the tick from display: none](https://meta.codidact.com/uploads/2os0y2dc4c89l1xv0qf5o61u8f4m)

![Page and developer window after removing the tick from display: none](https://meta.codidact.com/uploads/1s7gof5w4ave3ud9hix33tds8z38)

## Workaround

1. Click on tools (this positions the panel correctly so it doesn't appear on a random part of the page later, but it's still invisible at this stage)
2. Open the developer window (F12)
3. Go to the Elements tab at the top
4. In the HTML that appears, look under `<body>` for the `<main>` tag. Click on the little arrows to open `<main>` and then it's child, grandchild, and great grandchild. You should now be able to see an HTML comment in green: `<!-- THREAD STARTS BELOW -->`
5. Two lines down from the green comment is a `<div>` with `class="droppanel"`. Click on this line so that it gets selected with a grey background
6. The styles for this element should now be visible in another panel. In my screenshot the panel is below the HTML filled panel, but for you it may be to the right.
7. In the styles panel find the section starting `.droppanel {` (there are 2 - it's the second one) and find the line that says `display: none;`
8. Next to `display: none;` is a checkbox. Untick it.
9. All of the hidden drop panels on the page should now become visible. This isn't ideal, but luckily the tools panel that you want is in front of the others so easily usable.

If at any point anything goes wrong, refreshing the page will set it all back as it was.

**Comment by trichoplax** [comment]
I've tested in development to see if the fix for #923 will also fix this bug. Bringing in the fixed Co-Design code results in the notifications panel and communities panel opening fine, whether clicking on the white area around them or directly on the icons. However, the tools panel still doesn't open, whether clicking on the cog, the word "tools" or the white area nearby.

So this is a different bug.

**Comment by cellio** [comment]
Is this a co-design bug or a qpixel bug?  Either way, we need to fix it -- just not sure where it belongs.

**Comment by ArtOfCode-** [comment]
Fixed by 824d75d89c65570780bf0a1e7edc279b1ec28d5b
